#server:
#  port: 8081
#
#
#
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 1067279544458-arn10hti8n4ivojd397gtdjrbps6diio.apps.googleusercontent.com
#            clientSecret: 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
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profileserver:
#  port: 8081
#
#
#
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 1067279544458-arn10hti8n4ivojd397gtdjrbps6diio.apps.googleusercontent.com
#            clientSecret: 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
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile